# Generated by Django 4.2.11 on 2024-04-01 14:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('trailer', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('poster', models.ImageField(upload_to='')),
                ('production_country', models.CharField(max_length=50)),
                ('age_restrictions', models.CharField(max_length=50)),
                ('duration', models.PositiveSmallIntegerField()),
                ('movie_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(1)])),
                ('seat_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('ticket', models.CharField(choices=[('NORMALNY', 'normalny'), ('ULGOWY', 'ulgowy')], default='NORMALNY', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_time', models.DateTimeField()),
                ('movie_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bilety.movie')),
            ],
        ),
    ]
