# Generated by Django 4.2.11 on 2024-04-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilety', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_type',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('FAMILIJNY', 'familijny'), ('HORROR', 'horror'), ('THILLER', 'thriller'), ('KOMEDIA', 'komedia'), ('ROMANS', 'romans')], default='komedia', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_restrictions',
            field=models.CharField(choices=[('B/O', 'b/o'), ('OD 15 LAT', 'od 15 lat'), ('OD 18 LAT', 'od 18 lat')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
