# Generated by Django 4.2.11 on 2024-04-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilety', '0002_remove_movie_movie_type_movie_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_restrictions',
            field=models.CharField(choices=[('B/O', 'b/o'), ('OD 13 LAT', 'od 13 lat'), ('OD 18 LAT', 'od 18 lat')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
