# Generated by Django 4.2.11 on 2024-04-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilety', '0003_movie_slug_alter_movie_age_restrictions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
