# Generated by Django 4.2.11 on 2024-04-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilety', '0004_alter_movie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='screening_time',
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
