# Generated by Django 4.2.11 on 2024-04-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilety', '0005_remove_room_screening_time_alter_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_restrictions',
            field=models.CharField(choices=[('b/o', 'b/o'), ('od 13 lat', 'od 13 lat'), ('od 18 lat', 'od 18 lat')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('familijny', 'familijny'), ('horror', 'horror'), ('thriller', 'thriller'), ('komedia', 'komedia'), ('romans', 'romans')], default='komedia', max_length=50),
        ),
        migrations.AlterField(
            model_name='seat',
            name='ticket',
            field=models.CharField(choices=[('normalny', 'normalny'), ('ulgowy', 'ulgowy')], default='normalny', max_length=15),
        ),
    ]
