# Generated by Django 4.2.11 on 2024-05-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilety', '0006_alter_movie_age_restrictions_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='screening_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='screening_time',
            field=models.TimeField(null=True),
        ),
    ]
