# Generated by Django 4.2.11 on 2024-05-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilety', '0007_room_screening_date_room_screening_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='ticket',
        ),
    ]
