# Generated by Django 4.2.11 on 2024-05-12 20:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilety', '0008_remove_seat_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='screening_room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bilety.room'),
        ),
        migrations.AddField(
            model_name='seat',
            name='ticket',
            field=models.CharField(choices=[('normalny', 'normalny'), ('ulgowy', 'ulgowy')], default='normalny', max_length=15),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bilety.seat')),
            ],
        ),
    ]
