# Generated by Django 4.2.11 on 2024-05-12 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilety', '0009_seat_screening_room_seat_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='screening_room',
        ),
        migrations.AddField(
            model_name='room',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bilety.seat'),
        ),
    ]
