# Generated by Django 4.2.11 on 2024-05-12 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilety', '0010_remove_seat_screening_room_room_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='seat',
        ),
        migrations.AddField(
            model_name='seat',
            name='screening_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bilety.room'),
        ),
    ]
