# Generated by Django 5.0.6 on 2024-05-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilety', '0013_remove_seat_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='ticket',
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket',
            field=models.CharField(choices=[('normalny', 'normalny'), ('ulgowy', 'ulgowy')], default='normalny', max_length=15),
        ),
    ]
